### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by limafresh** [SarthakTools/Currency-Converter#1]
There is only README in the repository.

**Comment by SarthakTools** [comment]
> There is only README in the repository.

Sorry for the inconvenience pls check the repository again i have uploaded the code again.

**Comment by limafresh** [comment]
**I am understand.** If you want, please see my CustomTkinter Painting app:

https://github.com/limafresh/Brushshe

![screenshot](https://github.com/user-attachments/assets/a3a1a3a4-55b6-4c83-8bd1-a92ca9fcdd54)

**Comment by SarthakTools** [comment]
> **I am understand.** If you want, please see my CustomTkinter Painting app:
> 
> https://github.com/limafresh/Brushshe
> 
> ![screenshot](https://private-user-images.githubusercontent.com/173814432/387288780-a3a1a3a4-55b6-4c83-8bd1-a92ca9fcdd54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxOTk1ODksIm5iZiI6MTczMjE5OTI4OSwicGF0aCI6Ii8xNzM4MTQ0MzIvMzg3Mjg4NzgwLWEzYTFhM2E0LTU1YjYtNGM4My04YmQxLWE5MmNhOWZjZGQ1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxNDI4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjMzZmNjMGE4OThlOTQwY2JhYjY4NjE0N2EyZmM2YmE3ODVjZWNhYjJjMGE3OWY3MTdlMDhhMWE3MmEwMjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6mZQZHEoHSR5yvglDNO7uCnKHOpuv0Ku7VN2MhHGxiY)

Very nice painting dude great painting i could not paint this good even on paper and you painted on computer.

**Comment by limafresh** [comment]
Thanks)
